### PR TITLE
label_colormap to return 0 and num_colors

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
This fixes the issue https://github.com/napari/napari/pull/5154#issuecomment-1263148405 with a single surface:
```
import napari
from napari.utils.colormaps import label_colormap

import numpy as np

vertices = np.array([[0, 0], [0, 20], [10, 0], [10, 10]])
faces = np.array([[0, 1, 2], [1, 2, 3]])
values = np.linspace(0, 1, len(vertices))
surface = (vertices, faces, values)

viewer = napari.view_surface(surface, colormap=label_colormap(1))  # add the surface
```
And stardist-napari seems happy too although I can't replicate the old issue https://github.com/napari/napari/issues/2352

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [x] example: all tests pass with my change: I ran pytest locally
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
I hope I did this correctly, still getting the hang of git/github.

**Comment by perlman** [comment]
We should modify the doc string indicate that the function returns transparent + N colors.

Did you find any other problem with the extra color? I had done this with my initial fix, but never pushed it in case there was some unintended consequence.

**Comment by perlman** [comment]
Peter, I'm going to push a file I had staged but never pushed to do the same thing.

Would you mind trying it out? Thanks!

**Comment by psobolewskiPhD** [comment]
@perlman I see the other branch, so I thought:
`git pull perlman label_colormap_exception_fix`
(I have your fork as a remote `perlman`)
```
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), 636 bytes | 57.00 KiB/s, done.
From https://github.com/perlman/napari
 * branch              label_colormap_exception_fix -> FETCH_HEAD
   3831378d..a7e8fec4  label_colormap_exception_fix -> perlman/label_colormap_exception_fix
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```
Any advice?
Sorry I'm still really not sure about most of this git stuff.

**Pull request closed without merging**
